include: package:lint/analysis_options.yaml

linter:
  rules:
    - parameter_assignments

analyzer:
  exclude:
    - lib/**/*.freezed.dart
    - lib/**/*.g.dart
    - lib/presentation/routes/auto_router.gr.dart
    - lib/injection.config.dart
  errors:
    missing_required_param: error
    parameter_assignments: error
    missing_return: error